using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Efficient_Automatic_Traveler_System
{
    class KanbanItem
    {
        #region Public Methods
        public KanbanItem(Form form)
        {
            Update(form);
        }
        public KanbanItem(string json)
        {
            Dictionary<string, string> obj = new StringStream(json).ParseJSON();
            m_itemCode = obj["itemCode"];
            m_minStockQty = Convert.ToInt32(obj["minStockQty"]);
            m_injectionQty = Convert.ToInt32(obj["injectionQty"]);
        }
        public KanbanItem(string itemCode, int minStockQty, int injectionQty)
        {
            m_itemCode = itemCode;
            m_minStockQty = minStockQty;
            m_injectionQty = injectionQty;
        }
        public override string ToString()
        {
            Dictionary<string, string> obj = new Dictionary<string, string>()
            {
                {"itemCode",m_itemCode.Quotate() },
                {"minStockQty", m_minStockQty.ToString() },
                {"injectionQty", m_injectionQty.ToString() }
            };
            return obj.Stringify();
        }
        public static NodeList CreateMonitorHeader()
        {
            Style borderStyle = new Style("kanban__border");
            NodeList row = new NodeList(DOMtype: "tr");
            row.Add(new Node(new Style("kanban__border"), DOMtype:"td"));
            row.Add(new TextNode("Current", new Style("kanban__border"), DOMtype: "th"));
            row.Add(new TextNode("Min Qty", new Style("kanban__border"), DOMtype: "th"));
            row.Add(new TextNode("Item Code", new Style("kanban__border"), DOMtype: "th"));
            row.Add(new TextNode("Qty Queued", new Style("kanban__border"), DOMtype: "th"));
            row.Add(new TextNode("Traveler Qty", new Style("kanban__border"), DOMtype: "th"));
            return row;
        }
        public NodeList CreateMonitorRow(int rowIndex)
        {
            NodeList row = new NodeList(DOMtype: "tr");
            double x = (double)Math.Max(0, m_stockQty - MinStockQty) / (double)MinStockQty;

            byte red = (byte)Math.Min(255, 2.0 * (1 - x) * 255);
            //byte green = (byte)Math.Min(255, (((double)Math.Max(0, m_stockQty - MinStockQty) / (double)MinStockQty)) * (double)255);
            byte green = (byte)Math.Min(255, (255 * x * 2.0));

            Style color = new Style();
            color.AddStyle("backgroundColor", ("rgb(" + red + ',' + green + ",0)"));

            row.Add(new Node(new Style("kanban__colorBox") + color, DOMtype: "td"));
            row.Add(new TextNode(m_stockQty.ToString(), new Style("kanban__border"), DOMtype: "td"));
            row.Add(new TextNode(m_minStockQty.ToString(), new Style("kanban__border"), DOMtype: "td"));
            row.Add(new TextNode(ItemCode, new Style("kanban__border"), DOMtype: "td"));
            row.Add(new TextNode(m_qtyOnTraveler.ToString(), new Style("kanban__border"), DOMtype: "td"));
            row.Add(new TextNode(InjectionQty.ToString(), new Style("kanban__border"), DOMtype: "td"));
            row.Add(new NodeList(DOMtype: "td")
            {
                { new Button("","EditKanbanItemForm", @"{""itemCode"":" + m_itemCode.Quotate() + "}",style: new Style("editBtn")) }
            });
            row.Add(new NodeList(DOMtype: "td")
            {
                { new Button("", "DeleteKanbanItem",@"{""itemCode"":" + m_itemCode.Quotate() + "}",style: new Style("deleteBtn")) }
            });
            return row;
        }
        public void Update(int stockQty, int qtyOnTraveler)
        {
            m_stockQty = stockQty;
            m_qtyOnTraveler = qtyOnTraveler;
            while (m_stockQty + m_qtyOnTraveler < m_minStockQty)
            {
                // ADD A NEW TRAVELER (TO START)
                // IF TABLE, add to Heian2
                Traveler traveler = Server.TravelerManager.AddTraveler(m_itemCode, m_injectionQty);
                traveler.Comment = "Generated by kanban";
                if (traveler is Table)
                {
                    traveler.Station = StationClass.GetStation("Heian2");
                    traveler.EnterProduction(Server.TravelerManager);
                }
                m_qtyOnTraveler += m_injectionQty;
            }
        }

        public static Form CreateForm()
        {
            Form form = new Form();
            form.Title = "Kanban Item";
            form.Textbox("itemCode", "Item Code");
            form.Integer("minStockQty", "Minimum balance", min: 1, value:1);
            form.Integer("injectionQty", "Traveler quantity", min: 1, value:1);
            return form;
        }

        public Form CreateFilledForm()
        {
            Form form = new Form();
            form.Title = "Kanban Item";
            form.Textbox("itemCode", "Item Code", m_itemCode);
            form.Integer("minStockQty", "Minimum balance", min: 1, value: m_minStockQty);
            form.Integer("injectionQty", "Traveler quantity", min: 1, value: m_injectionQty);
            return form;
        }

        public void Update(Form form)
        {
            m_itemCode = form.ValueOf("itemCode");
            m_minStockQty = Convert.ToInt32(form.ValueOf("minStockQty"));
            m_injectionQty = Convert.ToInt32(form.ValueOf("injectionQty"));
        }
        #endregion
        #region Properties
        private string m_itemCode;
        private int m_stockQty;
        private int m_qtyOnTraveler;
        private int m_minStockQty;
        private int m_injectionQty; // cuz it sounds cool


        #endregion
        #region Interface
        public string ItemCode
        {
            get
            {
                return m_itemCode;
            }

            set
            {
                m_itemCode = value;
            }
        }

        public int MinStockQty
        {
            get
            {
                return m_minStockQty;
            }

            set
            {
                m_minStockQty = value;
            }
        }

        public int InjectionQty
        {
            get
            {
                return m_injectionQty;
            }

            set
            {
                m_injectionQty = value;
            }
        }
        #endregion
    }
}
